### ISSUE TITLE
Untested libraries

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [gelisam/frp-zoo#24]
I suggest removing the untested libraries from the chart, they are just wasting space, and just listing them in a paragraph instead.

**Comment by gelisam** [comment]
Good idea. Or perhaps I could remove them entirely and file issues to add them instead? It would be more consistent: that list simply represents all the FRP libraries I could find at the moment I created the zoo, and whenever I've encountered other libraries since then, I've been adding them as issues instead of as new untested entries in the list.

**Comment by jeffreyrosenbluth** [comment]
I agree, I think the best place for the untested libraries is in the issues.

**Comment by gelisam** [comment]
I have filed one issue per library, closing.

I think I'll send emails to the maintainers of those libraries to ask them if they want to contribute an implementation. At 120 stars, I think we're big enough now that they's have an incentive to contribute :)
