### ISSUE TITLE
Graphics.Gloss.Data.Extent is not exposed

### ISSUE THREAD

**Issue by madjestic** [gelisam/frp-zoo#50]
It looks like gloss does not expose Graphics.Gloss.Data.Extent interface since 1.9.1.1,
hence examples do not compile with recent gloss versions.

**Comment by gelisam** [comment]
Graphics.Gloss.Data.Extent has moved from gloss to gloss-algorithms in gloss-1.9.1.1. All the examples include a cabal file which include gloss-algorithms and requires gloss 1.9.2.1 or later.

Both cabal and stack should pick up that information from the cabal file, so I don't understand why that didn't work for you. Which tool did you use in order to compile the examples?
